### ISSUE TITLE
Communication between Host and CBH is blocked!

### ISSUE THREAD

**Issue by ZYXing666** [AndriyChmyrov/olympusix#1]
Hello, Olympusix. Are you a technical developer at Olympus?

I may need your technical support. Our questions are as follows:

When we were developing software for IX83 microscope control, we encountered some issues. We have two computers, one of which can send commands to CHB normally. The same program on the other computer, Host, can send a command to CHB and receive a response, but the second command fails to send successfully. This issue also occurs when running the official example file gt_cmd_test.exe. Through analysis of the log file, we believe it is a problem with the fsi1394 driver.

msl_pm.log: “+++ Submit failed, cmd=0x14fb38, cmd->Type=0x0, B<A:1 +++”
msl_pd_1394.log: “Exit MSL_PD_WritePort, Seq=1, ulLen=15, retryCount=12”
fsi1394.log: *** PACKET TRANSMISSION FAILURE ( ERR : 0x3DCF558 ) ***

Thanks!

**Comment by AndriyChmyrov** [comment]
Hello Yongxing Zhang,

I am not related to Olympus in any way, so sorry that I can't help you.
Since you have 2 computers next to each other, it should be possible to figure out the difference.
Check in DeviceManager that you have properly installed drivers for IEE1394 card and for the Olympus IX3-CBH controller.  It might be that not all IEE1394 cards are compatible. As far as I recall - Olympus provides IEE1394 drivers as well. Maybe try the card from the computer which works well on the other one and so on - then you could figure out if it is the card or the driver.

Not sure that I can help more.
Good luck!
